# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -v -o prom-opendata-zh-parking-darwin-arm64
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -v -o prom-opendata-zh-parking-darwin-amd64
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -v -o prom-opendata-zh-parking-linux-amd64
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -v -o prom-opendata-zh-parking-linux-arm64
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -v -o prom-opendata-zh-parking-windows-amd64
        GOOS=windows GOARCH=arm64 go build -ldflags "-s -w" -v -o prom-opendata-zh-parking-windows-arm64

    - name: GH Release
      uses: softprops/action-gh-release@v2.0.8
      with:
          files: |
            prom-opendata-zh-parking-darwin-arm64
            prom-opendata-zh-parking-darwin-amd64
            prom-opendata-zh-parking-linux-amd64
            prom-opendata-zh-parking-linux-arm64
            prom-opendata-zh-parking-windows-amd64
            prom-opendata-zh-parking-windows-arm64
          generate_release_notes: true
          make_latest: true
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/emy/prom-opendata-zh-parking:latest